[package]
authors = ["Sam Rose <sam@cvpartner.com>"]
edition = "2018"
name = "rust-debugger"
version = "0.1.0"

[dependencies]
human-panic = "*"
libc = "0.2"
rustyline = "6.1.1"
log = "0.4.0"
env_logger = "0.7.1"
iced-x86 = "1"
gimli = "0.20"
memmap = "0.7"
object = "0.18"